### ISSUE TITLE
No longer supoorted OOS 12+ version!

### ISSUE THREAD

**Issue by DineshValor** [Xposed-Modules-Repo/com.alex193a.paextender#3]
Tested and work on last Android 11.

**Comment by StormPooper** [comment]
Can confirm after updating my OnePlus 7 Pro from OOS 11 to 12, the apps selected in PA Extender no longer appear as options in App cloner (as it has been renamed, under the Apps section of Settings). I've also tried the module for "App cloner" (com.oplus.multiapp) and System Framework on top of the recommended Settings, but no luck.

**Comment by DineshValor** [comment]
> Can confirm after updating my OnePlus 7 Pro from OOS 11 to 12, the apps selected in PA Extender no longer appear as options in App cloner (as it has been renamed, under the Apps section of Settings). I've also tried the module for "App cloner" (com.oplus.multiapp) and System Framework on top of the recommended Settings, but no luck.

Yep, bcoz OOS12+ update contain mix source code of ColorOS too.

**Comment by StormPooper** [comment]
Thought that might be the reason. Most suggestions I've seen online talk about installing APKs manually as user 999 (`adb install --user 999 <appname>.apk`), though obviously that's not as nice as what this module previously provided as you'd have to manually update them and it apparently doesn't play nice with Google apps. Not tried it myself yet, but thought I'd mention it for anyone looking for workarounds.

**Comment by DineshValor** [comment]
> Thought that might be the reason. Most suggestions I've seen online talk about installing APKs manually as user 999 (`adb install --user 999 <appname>.apk`), though obviously that's not as nice as what this module previously provided as you'd have to manually update them and it apparently doesn't play nice with Google apps. Not tried it myself yet, but thought I'd mention it for anyone looking for workarounds.

Yep, this can be done via terminal command, i saw too related stuff in different forums online. U need to type package name instead appname.apk

Well, thought so u just might given a hint, i guess.

**Comment by DineshValor** [comment]
> Thought that might be the reason. Most suggestions I've seen online talk about installing APKs manually as user 999 (`adb install --user 999 <appname>.apk`), though obviously that's not as nice as what this module previously provided as you'd have to manually update them and it apparently doesn't play nice with Google apps. Not tried it myself yet, but thought I'd mention it for anyone looking for workarounds.

Found a easy method, required root access.
Check this post:
https://forum.xda-developers.com/t/root-tasker-app-oneplus-parallel-app-installer.4342603/

**Comment by alex193a** [comment]
I've released a new module compatible with OxygenOS 13 (and theoretically OOS 12): [One Plus App Cloner Extender](https://github.com/Xposed-Modules-Repo/com.alex193a.opacextender)
